---
- name: Start the database docker container
  docker_container:
    name: mysql
    image: mysql/mysql-server:5.7
    env:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "linnea123"
    ports:
      - "3307:3307"
    restart_policy: always