version: "3.9"  # optional since v1.27.0
networks:
    monitor:

volumes:
    microblog-db: {}

services:
    prod:
        container_name: microblog
        image: linnea123/microblog:latest
        restart: always
        environment:
            - MYSQL_DATABASE=microblog
            - 'mysql+pymysql://microblog:hRTXk5_A^6!J@localhost:3307/microblog'
        ports:
            - "8000:5000"
        depends_on:
            - db
    db:
        image: mysql/mysql-server:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'microblog'
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'microblog'
            MYSQL_PASSWORD: 'linnea123'
        ports:
          - '3307:3307'
        expose:
          - '3307'
        volumes:
          - microblog-db:/var/lib/mysql
    test:
        build:
            context: .
            dockerfile: ./docker/Dockerfile_test
        volumes:
            - "./tests/:/home/microblog/tests/"
        restart:
            "no"