global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: nginx
    metrics_path: /prometheus
    scrape_interval: 30s
    static_configs:
      - targets: [ "{{ groups['loadBalancer'][0] }}:9111" ]