global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-:9100"]
  - job_name: "prometheus"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: nginx
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["0.0.0.0:9113"]