# Please see doc for version: https://circleci.com/docs/configuration-reference
version: 2.1

# Please see doc for orbs: https://circleci.com/docs/orb-intro
orbs:
    python: circleci/python@2.1

# Please see doc for jobs: https://circleci.com/docs/configuration-reference#jobs
jobs:
  build:
    docker:
      - image: cimg/python:2.7
    working_directory: ~/repo
    steps:
        # Step 1: obtain repo from GitHub
        - checkout
        # Step 2: create virtual env and install dependencies
        - run:
          name: create venv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
        # Run tests
        - run:
            python3 -m venv venv
            name: Run tests
            command: |
                . venv/bin/activate
                make test
