version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
        - checkout
        # Install dev and dependencies
        - run:
            name: install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt                pip install -r pylint
        # run tests
        - run:
            name: run tests
            command: |
                . venv/bin/activate
                make test
