# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests
      # Step 4: Build
      - build:
        executor: docker-publisher
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Docker image
                command: |
                    docker build -t $IMAGE_NAME:latest -f docker/Dockerfile_prod .
            - run:
                name: Archive Docker image
                command: docker save -o image.tar $IMAGE_NAME
            - persist_to_workspace:
                    root: .
                    paths:
                        - ./image.tar
      # Step 5: Publish to Dockerhub
      - publish-latest:
            executor: docker-publisher
            steps:
              - attach_workspace:
                  at: /tmp/workspace
              - setup_remote_docker
              - run:
                  name: Load archived Docker image
                  command: docker load -i /tmp/workspace/image.tar
              - run:
                  name: Publish Docker Image to Docker Hub
                  command: |
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    docker push $IMAGE_NAME:latest
      # Step 6: Publish tag
      publish-tag:
      executor: docker-publisher
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - setup_remote_docker
        - run:
            name: Load archived Docker image
            command: docker load -i /tmp/workspace/image.tar
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              IMAGE_TAG=${CIRCLE_TAG/v/''}
              docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
              docker push $IMAGE_NAME:latest
              docker push $IMAGE_NAME:$IMAGE_TAG