# Please see doc for version: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: linnea123/microblog
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
    test:
      docker:
        - image: circleci/python:3.9

      working_directory: ~/repo

      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              make install-test
        # activate venv
        - run: echo "source ~/repo/venv/bin/activate" >> $BASH_ENV
    build:
        executor: docker-publisher
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Docker image
                command: |
                    docker build -t $IMAGE_NAME:latest -f docker/Dockerfile_prod .
            - run:
                name: Archive Docker image
                command: docker save -o image.tar $IMAGE_NAME
            - persist_to_workspace:
                    root: .
                    paths:
                        - ./image.tar

    publish-latest:
            executor: docker-publisher
            steps:
              - attach_workspace:
                  at: /tmp/workspace
              - setup_remote_docker
              - run:
                  name: Load Docker image
                  command: docker load -i /tmp/workspace/image.tar
              - run:
                  name: Publish Docker Image to Docker Hub
                  command: |
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    docker push $IMAGE_NAME:latest
    Deploy:
            docker:
              - image: circleci/python:3.9

            working_directory: ~/repo
            steps:
                - checkout
                - run:
                    name: install dependencies
                    command: |
                        python3 -m venv venv
                        . venv/bin/activate
                        make install-deploy
                # activate venv
                - run: echo "source ~/repo/venv/bin/activate" >> $BASH_ENV
                - run:
                    name: run playbook
                    command: |
                        . venv/bin/activate
                        cd ansible
                        ansible-playbook gather_vm_instances.yml app_server.yml
workflows:
  version: 2
  build-master:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - Deploy:
            requires:
                - publish-latest