# Please see doc for version: https://circleci.com/docs/configuration-reference
version: 2.1

# Python version
machine:
    python:
        version: 2.7.16

# Please see doc for orbs: https://circleci.com/docs/orb-intro
orbs:
    python: circleci/python@2.1

# Please see doc for jobs: https://circleci.com/docs/configuration-reference#jobs
jobs:
  build:
    docker:
      - image: cimg/python:2.7
    working_directory: ~/repo
    steps:
      #Checkout repo from GitHub
      - checkout
      # Create environment and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Run tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make test
