FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py test.sh Makefile  .pylintrc pytest.ini ./

RUN python -m venv .venv
# hadolint ignore=DL3059
RUN apk --no-cache add --virtual build-dependencies libffi-dev openssl-dev py-pip build-base \
  && pip install  --upgrade pip \
  && pip install  -r requirements.txt \
  && apk del build-dependencies
  
# hadolint ignore=DL3059
RUN apk add --no-cache bash  make cmake

ENV FLASK_APP microblog.py

RUN .venv/bin/pip3 install -r requirements.txt

RUN chmod +x test.sh \
&& chown -R microblog:microblog ./
USER microblog

ENTRYPOINT ["./test.sh"]