apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-rolebinding
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: default
roleRef:
  kind: ClusterRole
  name: ingress-nginx-role
  apiGroup: rbac.authorization.k8s.io
