apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }

    http {
      server {
        listen 80;
        server_name gullmak.live www.gullmak.live;  # Hantera både huvuddomänen och www

        # Proxy requests to /app to the microblog
        location /app {
          proxy_pass http://microblog:80;  # Adjust to your application service name and port
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        }
      }
    }
