name: Deploy microblog

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          az login --tenant 229ecd8f-0027-4293-bb33-19cab7e6b83d
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: linnea123/microblog
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile_prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microblog:1.0.0-prod
          labels: ${{ steps.meta.outputs.labels }}