name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_docker_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: linnea123/microblog:latest
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: linnea123/microblog:latest
          labels: ${{ steps.meta.outputs.labels }}

  security:
    name: Snyk Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@main
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
