name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: linnea123/microblog:latest
          labels: ${{ steps.meta.outputs.labels }}
