name: Run tests, then build and push

on: [push]

env:
  prometheus_multiproc_dir: /tmp

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install-dev
      - uses: actions/checkout@v3
      - name: Run tests
        run: make test

  build:
    needs: test
    uses: ./.github/workflows/publish_docker_image.yml
    secrets: inherit