name: Publish Docker image

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          az login --tenant 229ecd8f-0027-4293-bb33-19cab7e6b83d
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: linnea123/microblog
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: linnea123/microblog:latest
          labels: ${{ steps.meta.outputs.labels }}