# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml

  docker:
    needs: run_tests 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set docker tag
        run: echo "tag_name=$(cut -c2- <<< $GITHUB_REF_NAME)" >> $GITHUB_ENV
      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile_prod
          context: .
          push: true
          tags: ligm19/microblog2:${{ env.tag_name }}-prod