# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests on Python application

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  exec-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
      - name: Run tests
        run: make test

  python-snyk:
    needs: exec-tests
    uses: ./.github/workflows/python-snyk.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
