name: Run tests, build and push docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
    - name: Run tests and validation
      run: make test
    - name: Check out repo
      uses: actions/checkout@v3
    #Docker image
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASS
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: linnea123/microblog  
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: ./docker/Dockerfile_prod
        push: true
        tags: linnea123/microblog:${{ env.tag_name }}-prod
        labels: ${{ steps.meta.outputs.labels }}